[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
    "@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

# RPC Configuration
[rpc_endpoints]
base = "https://mainnet.base.org"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
